import { StyleSheet } from "react-native";
import React from "react";
import { Dimensions } from "react-native";

const windowWidth = Dimensions.get("window").width;
const windowHeight = Dimensions.get("window").height;

const styles = StyleSheet.create({
  ladowanie: {
    flex: 1,
  },
  kropk1: {
    justifyContent: "center",
    paddingTop: "13%",
  },
  img: {
    height: 424,
    width: 390,
    marginTop: -90,
  },
  tytul: {
    fontSize: 35,
    padding: 10,
    fontWeight: "bold",
    color: "#000",
    textAlign: "center",
    lineHeight: 40,
    marginTop: -40,
    marginBottom: 15,
  },
  podtytul: {
    fontSize: 18,
    padding: 10,
    color: "#000",
    lineHeight: 20,
    marginTop: -20,
    paddingLeft: 20,
    paddingRight: 20,
    letterSpacing: 1,
  },
  ladowanie1: {
    flex: 1,
  },
  splash: {
    alignSelf: "center",
    width: windowWidth,
    height: windowHeight / 2,
    resizeMode: "contain",
    marginTop: windowHeight / 2.7,
    maxHeight: 133,
    maxWidth: 200,
  },
  nextButton: {
    width: 300,
    height: 40,
    backgroundColor: "#5AE4A8",
    color: "#fff",
    alignItems: "center",
    marginRight: 45,
    borderRadius: 10,
    marginBottom: 20,
    shadowOffset: {
      width: 0,
      height: 3,
    },
    shadowOpacity: 0.2,
    shadowRadius: 2.62,
    elevation: 4,
  },
  skipButton: {
    marginBottom: windowHeight / 0.57,
    marginLeft: windowWidth / 2,
    marginRight: -windowWidth / 1.2,
    alignSelf: "center",
  },
  register: {
    flex: 1,
  },
  titleRegister: {
    width: 200,
    height: 34,
    fontWeight: "bold",
    fontSize: 32,
    marginTop: "5%",
    paddingTop: 9,
    marginLeft: "7%",
    color: "#000",
  },
  arrow: {
    width: 50,
    height: 50,
    marginTop: "15%",
    marginBottom: "3%",
    marginLeft: "5%",
  },
  arrowProduct:{
    width: 40,
    height: 40,
    marginTop: "15%",
    marginLeft: "5%",
    marginBottom:10,
  }
  ,
  bottomTitle: {
    width: 310,
    height: 50,
    fontSize: 12,
    color: "#C1C1C1",
    marginLeft: "7%",
    padding: 3,
  },
  label: {
    fontSize: 12,
    marginLeft: "7%",
    color: "#000",
  },
  box: {
    marginLeft: "6%",
    width: "88%",
    padding: 7,
    paddingLeft: 15,
    borderRadius: 10,
    columnGap: 10,
  },
  registerNextButton: {
    width: 349,
    height: 39,
    backgroundColor: "#5AE4A8",
    color: "#fff",
    alignItems: "center",
    borderRadius: 10,
    marginTop: "15%",
    marginBottom: "3%",
    marginLeft: "5%",
    shadowColor: "#000",
    shadowOffset: {
      width: 0,
      height: 3,
    },
    shadowOpacity: 0.2,
    shadowRadius: 2.62,
    elevation: 4,
  },
  titleAddCard: {
    width: 200,
    height: 34,
    fontWeight: "bold",
    fontSize: 32,
    marginTop: "5%",
    paddingTop: 9,
    marginLeft: "7%",
    color: "#000",
    marginBottom: 40,
  },
  checkTitleStyle: {
    fontSize: 12,
    color: "#C1C1C1",
  },
  addCardNaxtButton: {
    width: 349,
    height: 39,
    backgroundColor: "#5AE4A8",
    color: "#fff",
    alignItems: "center",
    borderRadius: 10,
    marginTop: "5%",
    marginBottom: "3%",
    marginLeft: "5%",
    shadowColor: "#000",
    shadowOffset: {
      width: 0,
      height: 3,
    },
    shadowOpacity: 0.2,
    shadowRadius: 2.62,
    elevation: 4,
  },
  main: {
    flex: 1,
    marginTop: "10%",
  },
  awatar: {
    height: 50,
    marginLeft: "5%",
    marginTop: "9%",
  },
  bell: {
    position: "absolute",
    marginLeft: "81%",
  },
  card: {
    flex: 1,
    width: 340,
    height: 180,
    alignItems: "center",
    justifyContent: "center",
    alignSelf: "center",
    marginBottom: "70%",
  },
  login:{
    flex: 1,
  },
  logo:{
    height: 250,
    width: 250,
    alignSelf: "center",
    marginTop: '30%',
  },
  rejest:{
    flexDirection: 'row',
    marginLeft: '25%',
  },
  profil: {
    flex: 1,
  },
  titleProfil: {
    width: 200,
    height: 34,
    fontWeight: "bold",
    fontSize: 32,
    marginLeft: "15%",
    color: "#000",
  },
  nameProfil:{
    fontSize: 26,
    color: "#000",
    fontWeight: "bold",
    alignSelf: "center",
    padding: 2,
    marginTop: '3%',
  },
  profilAwatar: {
    height: 80,
    width: 80,
    alignSelf: "center",
    marginTop: '3%',
  },
  mailProfil:{
    fontSize: 14,
    color: "#AEAEAE",
    alignSelf: "center",
    marginBottom: '15%',
  },
  transfer: {
    flex: 1,
  },
  titleTransfer: {
    width: 200,
    height: 34,
    fontWeight: "bold",
    fontSize: 26,
    marginLeft: "12%",
    marginBottom: "5%",
    color: "#000",
  },
  labelTransfer: {
    fontSize: 12,
    marginLeft: "7%",
    color: "#AEAEAE",
  },
  boxTransfer: {
    marginLeft: "6%",
    width: "88%",
    height: 65,
    padding: 7,
    paddingLeft: 15,
    columnGap: 10,
  },
  textTransfer:{
    color: "#AEAEAE",
    marginLeft: "80%",
    marginTop: -40,
  },
  logoTransferCompleted: {
    height: 150,
    width: 150,
    alignSelf: "center",
    marginTop: '30%',
  },
  titleTransferCompleted: {
    width: 311,
    height: 50,
    fontWeight: "bold",
    fontSize: 32,
    marginBottom: "5%",
    marginTop: "8%",
    color: "#000",
    alignSelf: "center",
  },
  send: {
    flex: 1,
  },
  titleSend: {
    width: 311,
    height: 50,
    fontWeight: "bold",
    fontSize: 26,
    marginBottom: "5%",
    marginLeft: "5%",
    color: "#000",
    alignSelf: "center",
  },
  selectPerson:{
    width: 220,
    height: 70,
    fontWeight: "bold",
    fontSize: 26,
    marginLeft: "7%",
  },
  labelSend: {
    fontSize: 12,
    marginLeft: "7%",
    color: "#AEAEAE",
  },
  boxSend: {
    marginLeft: "6%",
    width: "88%",
    height: 65,
    padding: 7,
    paddingLeft: 15,
    columnGap: 10,
  },
  lastSend:{
    width: 311,
    height: 40,
    fontWeight: "bold",
    fontSize: 26,
    marginBottom: "5%",
    marginLeft: "7%",
    color: "#000",
    marginTop: "8%",
  },
  avatarSend:{
    height: 66,
    width: 66,
    marginLeft: "7%",
  },
  profilAwatar2:{
    height: 80,
    width: 80,
    alignSelf: "center",
    marginTop: -15,
  },
  titleSend2: {
    width: 311,
    height: 50,
    fontWeight: "bold",
    fontSize: 26,
    marginLeft: "5%",
    marginTop: -15,
    color: "#000",
    alignSelf: "center",
  },
  send2Amount: {
    width: 349,
    height: 100,
    backgroundColor: "#fff",
    color: "#fff",
    alignItems: "center",
    borderRadius: 10,
    marginTop: "5%",
    marginLeft: "5%",
    shadowColor: "#000",
    shadowOffset: {
      width: 0,
      height: 3,
    },
    shadowOpacity: 0.2,
    shadowRadius: 2.62,
    elevation: 4,
  },
  send2ButtonTextAmount:{
    color: "#2F6B5B", 
    fontSize: 28,
    fontWeight: "bold", 
  },
  textSend2Amount:{
    marginTop: -95,
    marginLeft: "10%",
    fontSize: 18,
    fontWeight: "bold", 
  },
  send2Availablefunds:{
    marginTop: "11.5%",
    alignSelf: "center",
    fontSize: 15,
    fontWeight: "bold", 
  },
  send2NextButton: {
    width: 349,
    height: 39,
    backgroundColor: "#5AE4A8",
    color: "#fff",
    alignItems: "center",
    borderRadius: 10,
    marginTop: "6%",
    marginLeft: "5%",
    shadowColor: "#000",
    shadowOffset: {
      width: 0,
      height: 3,
    },
    shadowOpacity: 0.2,
    shadowRadius: 2.62,
    elevation: 4,
  },
  nameSend2:{
    fontSize: 26,
    color: "#000",
    fontWeight: "bold",
    alignSelf: "center",
    padding: 2,
  },
  mailSend2:{
    fontSize: 14,
    color: "#AEAEAE",
    alignSelf: "center",
    marginTop: -5,
    fontWeight: "bold",
  },
  labelSend2: {
    fontSize: 12,
    marginLeft: "7%",
    color: "#AEAEAE",
    
  },
  boxSend2: {
    marginLeft: "6%",
    width: "88%",
    height: 65,
    padding: 7,
    paddingLeft: 15,
    columnGap: 10,
    borderRadius: 10,
    shadowColor: "#000",
    elevation: 0.1,
  },
  keyboard:{
    marginBottom: -50,
  },
  namePerson:{
    height: 40,
    width: 200,
    fontWeight: "bold",
    fontSize: 26,
    color: "#000",
    marginTop: '6%',
    marginLeft: "5%",
  },
  iconProduct:{
    width: 110,
    height: 60,
    marginLeft: "5%",
    marginBottom:30,
    flexDirection: 'row',
    gap:25
  }
 
});

export default styles;
